version: '3.8'

services:
  react-table-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development