import { Person } from "../types/PersonTypes";

export const defaultData: Person[] = [
    {
        id: 1,
        firstName: "John",
        lastName: "Doe",
        age: 25,
        email: "john@example.com",
    },
    {
        id: 2,
        firstName: "Jane",
        lastName: "Smith",
        age: 32,
        email: "jane@example.com",
    },
    {
        id: 3,
        firstName: "Bob",
        lastName: "Johnson",
        age: 45,
        email: "bob@example.com",
    },
    {
        id: 4,
        firstName: "Alice",
        lastName: "Brown",
        age: 29,
        email: "alice@example.com",
    },
    {
        id: 5,
        firstName: "Charlie",
        lastName: "Davis",
        age: 35,
        email: "charlie@example.com",
    },
    {
        id: 6,
        firstName: "Eve",
        lastName: "Miller",
        age: 27,
        email: "eve@example.com",
    },
    {
        id: 7,
        firstName: "Frank",
        lastName: "Wilson",
        age: 38,
        email: "frank@example.com",
    },
    {
        id: 8,
        firstName: "Grace",
        lastName: "Moore",
        age: 30,
        email: "grace@example.com",
    },
    {
        id: 9,
        firstName: "Henry",
        lastName: "Taylor",
        age: 33,
        email: "henry@example.com",
    },
    {
        id: 10,
        firstName: "Ivy",
        lastName: "Anderson",
        age: 41,
        email: "ivy@example.com",
    },
    {
        id: 11,
        firstName: "Jack",
        lastName: "Thomas",
        age: 28,
        email: "jack@example.com",
    },
    {
        id: 12,
        firstName: "Karen",
        lastName: "Jackson",
        age: 39,
        email: "karen@example.com",
    },
    {
        id: 13,
        firstName: "Leo",
        lastName: "White",
        age: 44,
        email: "leo@example.com",
    },
    {
        id: 14,
        firstName: "Mia",
        lastName: "Harris",
        age: 23,
        email: "mia@example.com",
    },
    {
        id: 15,
        firstName: "Nathan",
        lastName: "Martin",
        age: 36,
        email: "nathan@example.com",
    },
    {
        id: 16,
        firstName: "Olivia",
        lastName: "Lee",
        age: 42,
        email: "olivia@example.com",
    },
    {
        id: 17,
        firstName: "Paul",
        lastName: "Garcia",
        age: 37,
        email: "paul@example.com",
    },
    {
        id: 18,
        firstName: "Quinn",
        lastName: "Martinez",
        age: 40,
        email: "quinn@example.com",
    },
    {
        id: 19,
        firstName: "Rachel",
        lastName: "Robinson",
        age: 31,
        email: "rachel@example.com",
    },
    {
        id: 20,
        firstName: "Steve",
        lastName: "Clark",
        age: 26,
        email: "steve@example.com",
    },
];